# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.


stages:
  - build
  - test
#  - sonar

build:
  stage: build
  script:
    - echo "commit"
    - ./gradlew assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    when: always
    paths:
      - build/reports/
  cache:
    key: ' $CI_COMMIT_REF_NAME'
    policy: pull-push
    paths:
      - build
      - .gradle

#sonar:
#  stage: sonar
#  script:
#    - ./gradlew jacocoTestReport sonar
#    - ./gradlew --stop

scan:
  stage: test
  script:
    - ./gradlew sonar -Pcoverage -D"sonar.host.url=$sonar_host_url" -D"sonar.token=$sonar_token" --info
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  dependencies:
    - test


