# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "commit"
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test

scan:
  stage: test
  script:
    - ./gradlew sonar -Pcoverage -Dsonar.host.url=$sonar_host_url -Dsonar.token=$sonar_token --info
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  dependencies:
    - test


