version: '3.9'  # Updated to the latest Compose file version for more features

services:
  # CuisineCraft Authentication Service
  cuisinecraft-auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cuisinecraft-auth
    ports:
      - "8080:8080"  # Map container port 8080 to host port 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://34.77.156.124:3306/ccauth  # Cloud SQL Public IP
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: arieldbpass
