#name: CI Pipeline
#
#on:
#  push:
#    branches:
#      - features       # Adjust this as needed
#  pull_request:
#    branches:
#      - features       # Adjust this as needed
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'adopt'
#
#      - name: Grant execute permissions to gradlew
#        run: chmod +x ./gradlew  # Ensures the gradlew script is executable
#
#      - name: Build with Gradle
#        run: ./gradlew assemble
#
#      - uses: actions/cache@v3
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-
#
#  test:
#    needs: build
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'adopt'
#
#      - name: Grant execute permissions to gradlew
#        run: chmod +x ./gradlew  # Ensures the gradlew script is executable
#
#      - name: Run tests
#        run: ./gradlew test
#
#      - uses: actions/upload-artifact@v3
#        with:
#          name: test-reports
#          path: build/reports/
#
#  scan:
#    needs: test
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'adopt'
#
#      - name: Grant execute permissions to gradlew
#        run: chmod +x ./gradlew  # Ensures the gradlew script is executable
#
#      - name: SonarQube Scan
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
#        run: |
#          ./gradlew sonar \
#            -Dsonar.projectKey=your_project_key \
#            -Dsonar.host.url=$SONAR_HOST_URL \
#            -Dsonar.login=$SONAR_TOKEN  # Ensures the gradlew script is executable

name: SonarQube Scan

on:
  push:
    branches:
      - features  # Adjust this as needed
  pull_request:
    branches:
      - features  # Adjust this as needed

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Checkout the code

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Grant execute permissions to gradlew
        run:
          chmod +x ./gradlew

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

       # Ensure gradlew is executable

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: ./gradlew build sonar --info


